version: '3.8'

services:

  php:
    image: php:7.4-apache
    restart: always
    container_name: php-apache-container
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - db-mysql

    volumes:
      - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin-container
    ports:
      - "8080:80"
    depends_on:
      - db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-container
      PMA_USER: root
      PMA_PASSWORD: root

  db-mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqlvolume:/var/lib/mysql
volumes:
  mysqlvolume:
